fs:
  image: tianon/true
  volumes:
    - ./conf:/etc/nginx/conf.d
    - ./certs:/etc/nginx/certs
    - ./certs-archive:/etc/letsencrypt/archive

proxy:
  image: eforce21/letsencrypt-nginx-proxy
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - fs
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro

# Remember to set environment variables on new virtualhosts:
# (the first one is required, the other one is recommended)
#    - VIRTUAL_HOST=beta-sso.dina-web.net
#    - LETSENCRYPT_EMAIL=dina@mail.dina-web.net
